services:
  cerebri:
    build: .
    entrypoint: /bin/sh -c "bash"
    tty: true
    stdin_open: true
    volumes:
      - ./workdir:/home/user/workdir
      - ..:/workdir/cerebri
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
