services:
  zephyr:
    build: .
    entrypoint: /bin/sh -c "bash"
    tty: true
    stdin_open: true
    volumes:
      - ./workspace:/workdir
      - ..:/workdir/cerebri
      - .vscode:/workdir/.vscode
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
